### ISSUE TITLE
[Proposal]: Tools and practices for FAIR research software

### ISSUE THREAD

**Issue by anenadic** [carpentries-incubator/proposals#176]
### 1. Lesson Topic

Tools and practices for FAIR (Findable, Accessible, Interoperable and Reusable) research software

### 2. Lesson Language

English

### 3. Draft materials

https://github.com/softwaresaved/fair-research-software

### 4. Requirements for existing materials

- [X] do your lesson materials conform to our [Code of Conduct](https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html#code-of-conduct-summary-view)?
- [X] are your materials already on GitHub and do they use The Carpentries [lesson template](https://github.com/carpentries/styles) or [The Carpentries Workbench](https://carpentries.github.io/workbench/)? (you can visit [the Workbench tutorial](https://carpentries.github.io/sandpaper-docs/) to learn more about how to use our lesson infrastructure).

### 5. New repository creation

- [ ] I need a new repository created

### 6. Transfer existing repository

- [X] my lesson meets both criteria in part 4 and I would like to transfer the repository to The Carpentries Incubator

### 7. Collaborators

@anenadic 
@steve-crouch

**Comment by tobyhodges** [comment]
Sorry this notification slipped through the net, @anenadic. 

Please go ahead and transfer the repository into the Incubator. I have created a maintainer team for the lesson (with you and @steve-crouch as members) and will add that team to the repo after the transfer has been completed.

**Comment by anenadic** [comment]
Done @tobyhodges - thank you!

**Comment by tobyhodges** [comment]
Thank you @anenadic. I will close this issue now that the repository is set up and you have the appropriate access. I will still receive notifications so please post back here if you have any questions!

**Comment by anenadic** [comment]
@tobyhodges - I could not add @sjaffa and @kkh451 to the maintainers team for this lesson as they are members of the Incubator GH organisation. Could you send them invitations please or let me know if there is something I can do. 🙏
